package chatbot;

public class UrunEkle extends javax.swing.JInternalFrame {

    /**
     * Creates new form UrunEkle
     */
    public UrunEkle() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        elektronik = new javax.swing.JMenu();
        cepMenu = new javax.swing.JMenuItem();
        bilgisayarMenu = new javax.swing.JMenuItem();
        televizyonMenu = new javax.swing.JMenuItem();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ürün Ekle");

        desktop2.setBackground(new java.awt.Color(204, 204, 204));
        desktop2.setForeground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout desktop2Layout = new javax.swing.GroupLayout(desktop2);
        desktop2.setLayout(desktop2Layout);
        desktop2Layout.setHorizontalGroup(
            desktop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        desktop2Layout.setVerticalGroup(
            desktop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 204));

        elektronik.setText("Elektronik");

        cepMenu.setText("Cep Telefonu");
        cepMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepMenuActionPerformed(evt);
            }
        });
        elektronik.add(cepMenu);

        bilgisayarMenu.setText("Bilgisayar");
        bilgisayarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgisayarMenuActionPerformed(evt);
            }
        });
        elektronik.add(bilgisayarMenu);

        televizyonMenu.setText("Televizyon");
        televizyonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                televizyonMenuActionPerformed(evt);
            }
        });
        elektronik.add(televizyonMenu);

        jMenuBar1.add(elektronik);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilgisayarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgisayarMenuActionPerformed
        // TODO add your handling code here:
        BilgisayarGui bilgisayar = new BilgisayarGui();
        desktop2.add(bilgisayar);
        bilgisayar.setVisible(true);

    }//GEN-LAST:event_bilgisayarMenuActionPerformed

    private void cepMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepMenuActionPerformed
        // TODO add your handling code here:
        CepTelefonGui telefon = new CepTelefonGui();
        desktop2.add(telefon);
        telefon.setVisible(true);

    }//GEN-LAST:event_cepMenuActionPerformed

    private void televizyonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_televizyonMenuActionPerformed

        TelevizyonGui tv = new TelevizyonGui();
        desktop2.add(tv);
        tv.setVisible(true);
    }//GEN-LAST:event_televizyonMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bilgisayarMenu;
    private javax.swing.JMenuItem cepMenu;
    private javax.swing.JDesktopPane desktop2;
    private javax.swing.JMenu elektronik;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem televizyonMenu;
    // End of variables declaration//GEN-END:variables
}
